rules:
  relevant_keywords:
    - "liver cirrhosis"
    - "hepatitis c"
    - "fatty liver disease"
    - "liver function test"
    - "liver cancer"
    - "liver biopsy"
    - "jaundice"
    - "ascites"
    - "alcoholic liver disease"
    - "nash"
  irrelevant_patterns:
    - "joke"
    - "weather"
    - "football"
    - "movie"
    - "diabetes"
    - "kidney stones"
    - "heart disease"
    - "lung disease"
    - "thyroid"
    - "cholesterol"
  vague_patterns:
    - "i need help"
    - "can you assist me"
    - "support"
    - "question"
    - "xyz"
    - "asdfgh"

examples:
  relevant:
    - "What are the symptoms of liver cirrhosis?"
    - "How is hepatitis C diagnosed?"
    - "What is the treatment for fatty liver disease?"
    - "How do I interpret liver function test results?"
    - "How is alcoholic liver disease treated?"
    - "What are the complications of liver failure?"
    - "How is liver cancer diagnosed?"
    - "How do I prepare for a liver biopsy?"
    - "What causes jaundice in adults?"
    - "What is the prognosis for NASH?"
  irrelevant:
    - "Tell me a joke."
    - "What's the weather today?"
    - "Who won the football game?"
    - "Show me the latest movie releases."
    - "What's the best diet for diabetes?"
    - "How to treat kidney stones?"
    - "What causes heart disease?"
    - "How to improve lung function?"
    - "What causes thyroid problems?"
    - "How to lower cholesterol?"
  vague:
    - "I need help."
    - "Can you assist me?"
    - "Support."
    - "Question."
    - "xyz"
    - "asdfgh"